title: Yifei's Notebook
description: A place to keep my notes on data science and other interesting stuffs!
theme: just-the-docs
favicon_ico: "/assets/images/snowman_icon_246031.ico"

url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
  
color_scheme: light

